language: java
jdk: oraclejdk8
notifications:
  email: false
  slack:
    secure: GrrdAizKa/qMab+Rzb6Zv7sGaXBcEbJjY258wUDheku3DC/TEHler1lgoVrnXxx5PFDXy0ztXnMSJ7Epg8k7+Itf1uxlJUmzm2XIHoJ9LvbmEZvE+lz7v7w4VyVG45m672fWo2FrPQj2FopFcRW8hQiNAY3DcRghFP9JztOlnow=
env:
  global:
    - TERM=dumb

before_install: '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || openssl aes-256-cbc -K $encrypted_0c9cfa39ea8e_key -iv $encrypted_0c9cfa39ea8e_iv -in keystore.jks.enc -out keystore.jks -d'
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
after_success: ./gradlew jacocoTestReport coveralls

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock

branches:
  except:
  - /^release-.*$/

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew curseforge -S
    on:
      all_branches: true
      repo: CyclopsMC/CyclopsCore
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: BEMYle1PPmd/qqRtZALxpRU/51aCImR5O5zzYQyQjzZg231e0oxNiCFbtAXSwvO9SvxPQvf0XN1wNpPEI2tL8d0jQVUG1A4GezQdbvoIn1ofPXWBP8cilUFO2HM9ljdHwFt3WD0wx6TC0CpzOGao8l72lFvXN1c/QREQNljkjQw=
    on:
      all_branches: true
      repo: CyclopsMC/CyclopsCore
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./gradlew uploadArchives -S
    on:
      all_branches: true
      repo: CyclopsMC/CyclopsCore
      condition: "$TRAVIS_BRANCH =~ ^(master|release).*$"
